version: '3'

services:
    db:
	image: mongo:latest 
	volumes:
	    - db-data:/data/db
    node-app:
	image: demo-service
	ports:
	   - "8000:3000"
	environment:
	   - MONGODB_URL=mongodb://mongodb:27017/demo
	   - PORT=3000

